### ISSUE TITLE
GPS logging saving hundreds of features per tick

### ISSUE THREAD

**Issue by bzeeb** [DMS-Aus/Roam#181]
Went for a five minute stroll and came back with 50 thousand features, surprisingly Roam was running fine with no lag, good sign it can handle extended logging at least.

**Comment by NathanW2** [comment]
Is this still the case.  I don't get that here when testing.

**Comment by bzeeb** [comment]
I'll test again when I get a chance, haven't tried the function since last October.

**Comment by rjwillson** [comment]
I tried the gps_log functionality in 2.4.2 with 2 different external GPS units and I also experienced the extremely high logging of points in a short time period. I thought I would get around this by using the setting to record points by map unit as per setting shown below. I tried setting this to 10 and 20 and assumed that because the map units should be in metres (CRS = UTM) that this would correspond to 10 and 20 m. This setting didn't seem to change the rate of logging as I accumulated almost 750 pts in approximately 1 minute and after walking no more than 20 m. I am recording into a SpatiaLite/sqlite file. My settings in the roam.config file are as follows:
camera: 0
configmanager:
  qgislocation: !!python/unicode 'C:/OSGeo4W/bin/qgis.bat'
fullscreen: false
gps:
  tracking:
    distance: 20
gpscenter: true
gpslogging: true
gpsport: !!python/unicode 'scan'
iconswithtext: true
keyboard: true
projectpaths: []

**Comment by rjwillson** [comment]
I tried the GPS logging again using the recent 2.5 release but was unsuccessful in trying to get Roam's GPS logging to limit the number of records recorded 

Similar to my tests from last time using 2.4.2 I tried restricting the number of records recorded using both the distance and time setting and I also tried two different coordinate reference systems (i.e., EPSG 4326—WGS 84 geographic and my preferred CRS for my location in Canada: EPSG 3162, a projected CRS based on NAD83).

I also tried two different file formats (GeoPackage and SpatiaLite) for the container file

Same results in all instances: that is regardless of settings individual records are recorded 11 to 12 times per second and this rate of data collection soon becomes unmanageable if out in the field for any length of time.

Are there any workarounds out there to make use of the GPS logging feature in Roam?

Right now I can use Roam for all of our field data collection needs except for recording a tracklog which I have to do in QGIS using the built-in GPS information panel to record tracklogs.

Would prefer to just use Roam because it is much faster, smoother and more finger friendly on a tablet

see clips

![image](https://cloud.githubusercontent.com/assets/11098144/23139982/2460fadc-f77d-11e6-9d2b-1c79ffbced09.png)

**Comment by bzeeb** [comment]
good grief I opened this in 2014, how time flies!

Thanks for the all the testing information, unfortunately no workarounds I am aware of.

Definitely a feature would be good to get working again, will be on the 2.6 list.

**Comment by rjwillson** [comment]
thanks bzeeb, time does indeed go by too quickly! 

Is it possible to elevate the issue to a high priority because taking a track log is often a core capability that users ask about to replace their existing GPS/GNSS units.

**Comment by bzeeb** [comment]
Added layer with name gps_log, fields id int, x string, y string
Enabled gps logging under settings

Tested, working fine now
