### ISSUE TITLE
Intermittent AppCrash on Map Rendering - Windows Server  

### ISSUE THREAD

**Issue by HeatherHillers** [DMS-Aus/Roam#196]
We are running Roam master (ok, it's a few weeks old.) on Windows.  I'm getting AppCrashes (so, it doesn't write to Roam.exe.log.  It just does the Windows Version of the seg fault) while it is loading the project.  Usually in the middle of loading layers.  This usually only happens the first time I run Roam.  Second start up, everything is fine.  We have a big and not so big raster as background.  If I take the big one out, it doesn't happen as often, but it still happens now and then, so it seems to depend on the size of the Project.  These Projects don't Crash qgis, at least as far as I can see.  I wasn't getting this on Linux, but I was running 2.2 there and 2.6 on Windows, so I can't really compare the two.  Any ideas?

**Comment by bzeeb** [comment]
Hi Heather, we spent some time mid December dealing with what sounds like a very similar issue in a separate project of ours. 

It was caused by the multi-threaded rendering introduced in 2.4, quoted below comment from Nathan as we fixed it:

"Seems to be related to using too many threads when rendering. I have set the limit in Roam to now only use 2 when ideal thread count is > 2 and 1 for everything else. Using max ideal threads seems to cause crashes in Roam and QGIS. This should also help save on device battery."

Can you please try the latest build and let us know if our recent fixes solved your issue as well?

**Comment by HeatherHillers** [comment]
Oh cool!  I'll try it today. We're going live with the project today so it's going to be insane!  But I should have time to set it up on my test system.

**Comment by HeatherHillers** [comment]
Hey,

It worked!  I haven’t seen a crash since the reinstall.  Thanks!  I’m so glad that’s over with!

Happy New Year,

Heather

**Comment by bzeeb** [comment]
Great to hear, definitely a mess trying to debug what was going on once everything was multi-threaded.

Hope you have a happy new year as well.

Regards,
Ben

**Comment by HeatherHillers** [comment]
I’m so glad you managed it.  I never would have been able to debug that.  You guys rock.
