### ISSUE TITLE
GPS Tracking for line and area features

### ISSUE THREAD

**Issue by PaulJupp** [DMS-Aus/Roam#201]
lines and areas can be created via logging of GPS rather than digitising from screen

**Comment by NathanW2** [comment]
Fixed in master.  Also added node at vertex options.

New tracking controls on in the GPS page

![image](https://cloud.githubusercontent.com/assets/381660/7061878/8e09a848-deda-11e4-8487-f6dbdf8736f0.png)

and the new toolbar

![image](https://cloud.githubusercontent.com/assets/381660/7061884/a82f6ce4-deda-11e4-959c-6202858ae112.png)
