### ISSUE TITLE
Multiple Imagery

### ISSUE THREAD

**Issue by StaleNZ** [DMS-Aus/Roam#224]
Hi again, I loaded two basemaps, is it possible to toggle them on/off individually? At the moment they both turn on together.

**Comment by bzeeb** [comment]
Hello, we plan to allow this in the config at some point, please see #23

**Comment by tristanfazio** [comment]
How are you doing the manual install if I may ask?

I have my projects set up on a server that I push to tablets. On the server I have the aerial in the projects folder as you mentioned (C:/Intramaps Roam/projects/latest_imagery.ecw) on the server and select it from QGIS. I push the install to the tablets and then put the aerial in the same location on the tablets, however it is still saying the layer is not found. Even though the path is exactly the same.

Do I need to install QGIS on the tablet and open the project file and manually select the layer through QGIS to have it referenced properly?

Cheers,

**Comment by bzeeb** [comment]
Hi Tristan, no you do not need to install QGIS on the tablet.

I have set up ECW files exactly the same way you described many times and it has worked fine for me.

Can you open your QGIS project file (.qgs) and check exactly what path the imagery is using in there? Then compare this to your Roam folder structure? Note it is usually a relative path rather than absolute.

**Comment by tristanfazio** [comment]
Hi Ben,

The tablet didn't have extensions on so when I copied it from the source and renamed it it ended up with ecw.ecw.

thanks for your help.
