### ISSUE TITLE
Record List Order

### ISSUE THREAD

**Issue by StaleNZ** [DMS-Aus/Roam#226]
I create a new vector layer with attributes A, B, C and these are placed in a form in the same order. Then I capture this layer in ROAM, but when I select the captured point to check its record, the order of the attributes appears to become random. 

How can I get them to stay in the same order as the form?

**Comment by bzeeb** [comment]
The order of items in the Info Panel will match the order of columns in the source data.

At the moment we only control the attribute display when the data is coming out of database layers from SQL Server and SQLite through the relevant SQL syntax:
http://roam-docs.readthedocs.org/en/latest/admin-guide/Select-Config/

I'm not sure how difficult it would be to extend the functionality to cover flat files (possibly using VirtualOGR?) so that they can also take the SQL syntax.
https://www.gaia-gis.it/fossil/libspatialite/wiki?name=VirtualOGR

**Comment by StaleNZ** [comment]
I still am having issues. Screenshot shows the info panel in ROAM and the table it is using in QGIS. The column order is not the same as the info panel. This is no major problem, but would be nice to arrange them in the same order as the table, what am I doing wrong?

![screenshot 2](https://cloud.githubusercontent.com/assets/10384504/5660076/254b85e8-971c-11e4-956b-37bd541c660b.png)

**Comment by NathanW2** [comment]
The ordering of attributes has only been fixed in the latest (unreleased) version.  You will need to build from source to get that fix.

**Comment by StaleNZ** [comment]
Great thanks, just tried it and looks good.
