### ISSUE TITLE
GPS Add Vertex Bug

### ISSUE THREAD

**Issue by skeenp** [DMS-Aus/Roam#300]
Using GPS while building features (using Add Vertex not Track) seems to occasionally adds additional points to a feature in odd ways.
- In some cases, vertex's are duplicated which is no so much a problem but makes features more complex than neccessary.
  ![image](https://cloud.githubusercontent.com/assets/9345597/10236626/65800dc2-68eb-11e5-8e1d-a6af9fc13dff.png)
- Of greater concern in the additional points away from the site. In one case, a number of additional vertex's were added at the same location around 500 meters from the actual site.
  ![image2](https://cloud.githubusercontent.com/assets/9345597/10236662/d5af29e8-68eb-11e5-98b6-0f7f4307fe7d.png)
  Output shapefile is available upon request if needed.

**Comment by bzeeb** [comment]
Thanks for reporting, I haven't seen this issue myself.

What kind of GPS are you using? I suspect it may be an issue with the data coming through from the device rather than Roam (not ruling that out though).

My best guess looking at the data is that the GPS is losing a proper fix sometimes which means the handheld device reverts back to a mobile network fix (based off the towers). This would explain the random jumps back to an identical point.

If you could attach raw GPS output logs alongside the shapefile created I would be interested to check through.

Regards,
Ben

**Comment by skeenp** [comment]
Will load GPS logs when the devices return, the units are dedicated Bluetooth GPS receivers and do not use towers. :)

**Comment by bzeeb** [comment]
Need some logging data to check what is going on here, gut feel is it related to GPS input rather than anything Roam is doing.

**Comment by skeenp** [comment]
I think the incorrect vertex was actually at the point where the button is for the add gps point. It seems that when the cursor leaves the map window and clicks the button, it occasionally adds a vertex. I've started noticing this again on a completely new tablet pc with new gps hardware and the latest build.
