### ISSUE TITLE
can i have a handwritten signature box in roam?

### ISSUE THREAD

**Issue by mickdillon** [DMS-Aus/Roam#356]
Is it possible to have a box or field that allows handwritten signatures to be entered into roam? I can easily add the photo field and take a photo using the built in camera of the tablet, so thought there must be some way of getting a jpg version of a signature in a similar way (without having to use pen and paper). Has anyone else out there been successful in finding a way to do this, or written some magical code to allow a signature  to be written in paint for example and then to be saved as a jpeg and linked to the field by unique id numbers?

**Comment by bzeeb** [comment]
You can easily do this by simply adding a photo field, then selecting either the folder icon (pick from file system) or the drawing pad (draw a signature in live).

If the signatures are known before hand it may be best to record the operator ID, then join this to your signature table back in the office to populate, rather than messing about in the field.
