### ISSUE TITLE
Intramaps translate

### ISSUE THREAD

**Issue by Gwen22200** [DMS-Aus/Roam#358]
Hi,

Can you tell me if is it possible to contribute to translate intramaps into french?
Do you have a language configuration file ?

Thanks a lot

Gwen

**Comment by bzeeb** [comment]
Hi Gwen, I believe it is already translated in to French:
https://github.com/DMS-Aus/Roam/blob/caded2720defe18e20a308be6c62616e23742375/src/roam/i18n/fr_FR.ts

Unfortunately there is a bug with the translation loader at the moment:
https://github.com/DMS-Aus/Roam/issues/211

If anybody has a working fix please let us know, otherwise we'll have a look and try to resolve for 2.6
