### ISSUE TITLE
[questions] for a newbie to Intramap Roam

### ISSUE THREAD

**Issue by osourcenewbie** [DMS-Aus/Roam#371]
Hello all, I'm new to using and programming Roam, so please bear with me.
I think this is an amazing tool and am looking forward to using it this summer to collect data!
I created a project, and an associated form based on a selected single shapefile in my qgis project (there are however, 10 shapefiles in the project). The form is meant to fill in the attribute data I am collecting in the field, and there is approximately 12 fields of data. I have tried using Roam and collecting some sample data, which seems to be populating the attribute data for the shapefile, however, the point data is not added to the map or displayed in qgis .  Here are my questions:
1. In the form builder of the Roam Config Manager, in the Configuration tab what is the difference between 'Capture Only', 'Save Only' and 'Capture and Save' in the Expression field? I seem to be only able to write to the attribute table of my shapefile if 'Capture Only' is selected.
2. Is there a way to auto increment the ID field in the attribute table?
3. If I were to add 2 more fields to the shapefile (or rebuild the shapefile) with Latitude and Longitude fields added, would there be a way to populate them from the GPS unit using the form builder?
Any advice you could pass on to me would be greatly appreciated. Thanks for your patience as I am sure I will have some more questions in the future.  Cheers!

**Comment by bzeeb** [comment]
Hi, great to hear you are finding Roam a useful tool!

For the issue you mentioned with the point not appearing, this is likely a style issue with the QGIS project. Mostly likely caused by your project file being a different version from Roam.

To explain simply, Roam is a touch friendly user interface built on top of QGIS, meaning that if you don't match the version of your QGIS desktop with your version of Roam the map display can come out different (although the vast majority of styles are cross-compatible).

You may check which version of QGIS Roam is using from the info box in the bottom right of the Settings page.

For your other questions:
1. This setting affects when the expression is run. Expression fields allow you to automatically populate form data based on basic queries.

2. Yes, if you use the expression field and open the builder you will find a special roam function we built just for this use-case:

![image](https://cloud.githubusercontent.com/assets/5965006/25571163/545f2678-2e5f-11e7-8fb9-0dde80944923.png)

3. Yes, again see the roam specific functions in expression builder. Try getting the GPS x/y/x fields out using these. Note you do not really need to capture this data in the shapefile as it is stored in the hidden geometry field, when you export the table to CSV it should automatically come out in plain text.

**Comment by osourcenewbie** [comment]
Hi all!
Figured out what was happening with respect to points not being added to the map. For some reason, the data collection layer was in a different projection than all of the other layers in qgis. Once I reset the projection voila! everything worked fine. I was also able to get the x and y coordinates to output into the form from the gps.
Thanks again for the advice!
